### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by ITheEqualizer** [Gozargah/Marzban-examples#17]
I've installed the panel using docker.

How can I change the panel password and how can I update to the latest version?

**Comment by Javad-Azimi** [comment]
It's my issue too

**Comment by naser2022** [comment]
go to: mazban directory >>>nano env >>>> change your username and password

**Comment by ef3pehr** [comment]
سلام 
من تک پورت رو نصب کردم چطوری میتونم به چند پورت آپگریدش کنم ؟ اصلا میشه یا باید اول تک پورت رو پاک کنم و مجدد چند پورتی رو نصب کنم.
اگر باید پاکش کنم میشه بفرمایید چطوری باید این کار رو بکنم ؟ ممنون
