### ISSUE TITLE
عدم اتصال به پنل

### ISSUE THREAD

**Issue by mrgdeveloper1401** [Gozargah/Marzban-examples#18]
با درود بیکرران و خسته نباشید به شما
من برای ورود به پنل مشکل دارم وقتی ادرس دامنه ام رو میزنم به پنل وارد نمیشه من قبلا روی پنل های سنایی و... با پورت وارد میشدم برای این چخ جور هست نصب رو از طریق تک پورت رفتم لطفا راهنمایی کنید با تشکر از لطف و عنایت شما

**Comment by Aramcodewp** [comment]
با سلام بنده هم با دامنه و سرور جدید اصلا دسترسی به پنل ندارم و ارور 526 را دریافت مینمایم. کلود فلر هم روی فول گذاشتم ولی تاثیری نداره.

**Comment by mrgdeveloper1401** [comment]
الان باید چی کار کنیم؟
