### ISSUE TITLE
باگ تغییر UUID

### ISSUE THREAD

**Issue by Cjxer** [Gozargah/Marzban-examples#19]
سلام خسته نباشید

من میخواستم از قسمت ادیت یوزر ، ترتیب پروتکل های یک کاربر رو تغییر بدم
و vmess کاربر رو خاموش کردم و سیو کردم
و مجدد ادیت یوزر رو زدم و اول تروجان رو روشن کردم و سپس vmess شو روشن کردم 
اما متوجه شدم که UUID توی vmess تغییر کرده و یک جدید جنریت شده
ممنون میشم پیگیری بفرمایید

قبل از خاموش کردن vmess
![Screenshot_20230525_035835](https://github.com/Gozargah/Marzban-examples/assets/26128739/ff801157-dad5-40c7-8e00-0bb49c00c18e)

بعد از خاموش و روشن کردن مجدد vmess
![Screenshot_20230525_040230](https://github.com/Gozargah/Marzban-examples/assets/26128739/53547efc-a2a1-4c80-8e41-c86d69f1e801)

با تشکر

**Comment by MrCjxer** [comment]
سلام مجدد

این مشکل هنوز پا برجا هست ، لطفا بگید که این مشکل هست یا نه ؟
چون من منتظر فیکس شدن این موضوع هستم و اگر قرار نیست فیکس بشه ، بگید تا من براش فکر دیگه ای بکنم
ممنون
