### ISSUE TITLE
domain

### ISSUE THREAD

**Issue by mlm1102003** [Gozargah/Marzban-examples#2]
hi
thanks for your affort
when add domain 
subscription cannt import to v2rayng android and v2rayn (subscription with domain)
and there is no qr code for subscription

**Comment by SaintShit** [comment]
@mlm1102003 Hi, Have you set XRAY_SUBSCRIPTION_URL_PREFIX in env file?
I can't say the problem with your subscription link without any further information, can you explain it more? and feel free to talk in a Persian if you know it

QR Code for subscription link is missing currently, but we're planning to add it in next update.

**Comment by mlm1102003** [comment]
سلام 
خسته نباشید ممنون بابت زحماتتون
وقتی XRAY_SUBSCRIPTION_URL_PREFIX فعال بشه لینک هایی که برای سابسکریپشن میده وقتی به برنامه میدیم قبول نمی کنه و کانفیگ ها اضافه نمیشه 
وقتی این غیر فعاله ولی سرت ها فعال می کنیم و با دامنه وارد میشیم ساب ها درست کانفیگ میدن 
مسیله بعدی 
قابلیت اضافه کردن کانفیگ های دیگه هست 
مثلا vlesstcp یا vlesstcptls و... هست که چطور میشه اضافه کرد ؟وقتی تنظیمات json رو تغییر میدم پنل کلا بالا نمیات

**Comment by SaintShit** [comment]
@mlm1102003 سلام. لینک سابسکریپشن رو توی مرورگر باز کنید و تست کنید آیا فایلی برای دانلود میاد؟ اگر نه، احتمالا توی کانفیگ کردن دامنه برای پنل درست عمل نکردید.
شما میتونید inbound های کانفیگ بیشتر کنید. فقط باید کمی کانفیگ xray وارد باشین. اگر پنلتون بعد از ادیت بالا نیومد، بهتره لاگ های برنامه رو بررسی کنید و ببینید چرا پنل لود نمیشه.

این متن رو مطالعه کنید: https://t.me/gozargah_marzban/1090
