### ISSUE TITLE
خطای /telegram_bot.php

### ISSUE THREAD

**Issue by Saliizan** [Gozargah/Marzban-examples#8]
سلام، آقا من با پیشنهاد خود مرزبان از طریق داکر و [Fully Single Port](https://github.com/Gozargah/Marzban-examples/tree/master/fully-single-port#en) رو روی سرور اوبونتو نصب کردم ولی لاگ که گرفتم یه خطای عجیبی به من می‌ده مشکل چیه دقیقا، راهنمایی کنی ممنونت می‌شم.

```
~/marzban#  docker compose logs
marzban-nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
marzban-nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
marzban-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
marzban-nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
marzban-nginx-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
marzban-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
marzban-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
marzban-nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
marzban-nginx-1  | 2023/02/21 23:36:07 [notice] 1#1: using the "epoll" event method
marzban-nginx-1  | 2023/02/21 23:36:07 [notice] 1#1: nginx/1.23.3
marzban-nginx-1  | 2023/02/21 23:36:07 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
marzban-nginx-1  | 2023/02/21 23:36:07 [notice] 1#1: OS: Linux 5.4.0-1086-kvm
marzban-nginx-1  | 2023/02/21 23:36:07 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
marzban-nginx-1  | 2023/02/21 23:36:07 [notice] 1#1: start worker processes
marzban-nginx-1  | 2023/02/21 23:36:07 [notice] 1#1: start worker process 27
marzban-nginx-1  | 2023/02/21 23:36:28 [error] 27#27: *1 open() "/etc/nginx/html/telegram_bot.php" failed (2: No such file or directory), client: 172.71.102.197, server: , request: "POST /telegram_bot.php HTTP/2.0", host: "www.safdiyet.com"
marzban-nginx-1  | 172.71.102.197 - - [21/Feb/2023:23:36:28 +0000] "POST /telegram_bot.php HTTP/2.0" 404 153 "-" "-" "91.108.6.155"
marzban-nginx-1  | 2023/02/21 23:38:05 [error] 27#27: *2 open() "/etc/nginx/html/telegram_bot.php" failed (2: No such file or directory), client: 172.71.94.15, server: , request: "POST /telegram_bot.php HTTP/2.0", host: "www.safdiyet.com"
marzban-nginx-1  | 172.71.94.15 - - [21/Feb/2023:23:38:05 +0000] "POST /telegram_bot.php HTTP/2.0" 404 153 "-" "-" "91.108.6.155"
marzban-nginx-1  | 2023/02/21 23:39:16 [error] 27#27: *3 open() "/etc/nginx/html/telegram_bot.php" failed (2: No such file or directory), client: 172.71.102.105, server: , request: "POST /telegram_bot.php HTTP/2.0", host: "www.safdiyet.com"
marzban-nginx-1  | 172.71.102.105 - - [21/Feb/2023:23:39:16 +0000] "POST /telegram_bot.php HTTP/2.0" 404 153 "-" "-" "91.108.6.155"
marzban-marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-marzban-1  | INFO:     Started server process [1]
marzban-marzban-1  | INFO:     Waiting for application startup.
marzban-marzban-1  | INFO:     2023/02/21 23:36:11 [Warning] core: Xray 1.7.2 started
marzban-marzban-1  | INFO:     Application startup complete.
marzban-marzban-1  | INFO:     Uvicorn running on unix socket /run/marzban.socket (Press CTRL+C to quit)
```

**Comment by savior128** [comment]
https://www.safdiyet.com/dashboard/login


خطایی نداره

**Comment by SaintShit** [comment]
@Saliizan سلام، این خطا مربوط به مرزبان نیست. داره روی اون پورت سرورتون درخواست میاد برای اون آدرس، ممکنه وب هوک تلگرام قبلا ست کرده باشید، یا اصلا ممکنه بات باشه. روی سرور های مجازی معمولا بات ها روی آیپی های مختلف درخواست های احتمالی میفرستن تا مشکل امنیتی پیدا کنند.

**Comment by SaintShit** [comment]
@Saliizan نه لازم نیست، مرزبان که مشکلی توی اجرا نداشته؟ کار میکنه؟ اون درخواست خیلی میاد؟

**Comment by Saliizan** [comment]
> @Saliizan نه لازم نیست، مرزبان که مشکلی توی اجرا نداشته؟ کار میکنه؟ اون درخواست خیلی میاد؟

راست تنظیمات هم و همه چی درست به نر میاد حتی ssl هم به درستی اوکی شد و من توی بخش ایکس‌ری بخش tls رو هم آنکامند کردم و دامنه خودم رو گذاشتم ولی وقتی http://{YOUR_SERVER_IP}:443/dashboard رو اجرا می‌کنم با دامنه خودم هیچ داشبوردی باز نمی‌شه و خطا می‌ده.
![Screen Shot 1401-12-03 at 13 09 17](https://user-images.githubusercontent.com/58263865/220582356-5699c424-514f-48dd-955c-10c21fb31102.png)

**Comment by Saliizan** [comment]
> اگر ssl فعال کردین https درخواست بفرستید با وی پی ان تست کنید شاید آیپی سرورتون فیلتر بود توی سرور با دستور `docker compose logs` چک کنید وقتی دستور میفرستید روی سرور میاد یا خیر؟ اگر از کلادفلر استفاده میکنید بخش SSL/TLS رو روی حالت Full بزارین
> 
> اینارو بررسی کنید

آقا با https پنل بالا امد الآن موارد رو بررسی می‌کنم، عشق به شما.

**Comment by Saliizan** [comment]
@SaintShit برادر سایتی که مثل کلادفلر خدمات بده و زیاد زیر نظر نباشه چیزی سراغ داری، یا اینکه ایرانی ولی اوکی باشه؟

**Comment by SaintShit** [comment]
@Saliizan خیر. این موارد رو میتونید توی گروه تلگرام با دوستان مشورت کنید.
لطفا اگر مشکل حل شد در آخر ایشو رو ببندید

**Comment by Saliizan** [comment]
> @Saliizan خیر. این موارد رو میتونید توی گروه تلگرام با دوستان مشورت کنید. لطفا اگر مشکل حل شد در آخر ایشو رو ببندید

چشم، امکانش هست لینک گروه رو بدید؟

**Comment by SaintShit** [comment]
@Saliizan t.me/gozargah_marzban
