### ISSUE TITLE
update & backup

### ISSUE THREAD

**Issue by shahrooz1349** [Gozargah/Marzban-examples#9]
hi dear developer
Thank you for developing this good panel
I installed with Docker How can I make the script update and backup the list of users?

regards

**Comment by AC-Lover** [comment]
You just need to backup the database
 Database path:
` /var/lib/marzban/db.sqlite3`
 To update with Docker, type the following commands

 `docker compose stop`
 `docker compose rm -f`
` docker compose pull`
 `docker compose up -d`

**Comment by shahrooz1349** [comment]
tnx dear developer
